server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix:
      classpath: /templates/
    suffix: .html
